1. Import numpy as np and see the version
- Import numpy as np and print the version number.

In [1]:
import numpy as np
print(np.__version__)

1.20.1


2. How to create a 1D array?
- Create a 1D array of numbers from 0 to 9

In [2]:
arreglo=np.arange(10)
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?
- Create a 3×3 numpy array of all True’s

In [3]:
bolean_array=np.full((3,3),True, dtype=bool)
bolean_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?
- Extract all odd numbers from arr

In [4]:
odd_array=arreglo[arreglo % 2 ==1]
odd_array

array([1, 3, 5, 7, 9])

5. How to replace items that satisfy a condition with another value in numpy array?
- Replace all odd numbers in arr with -1

In [5]:
arreglo=np.arange(10)
print(arreglo)
odd_array_completo=arreglo[arreglo % 2 ==1]=-1
odd_array_completo


[0 1 2 3 4 5 6 7 8 9]


-1

6. How to replace items that satisfy a condition without affecting the original array?

- Replace all odd numbers in arr with -1 without changing arr

In [11]:
arreglo2=np.arange(10)
odd_array_completo2=np.where(arreglo2 % 2 == 1, -1, arreglo2)
print(arreglo2)
odd_array_completo2

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7. How to reshape an array?

- Convert a 1D array to a 2D array with 2 rows

In [16]:
arreglo3=np.arange(10)
arreglo3=arreglo3.reshape(2,5)
arreglo3


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?

- Stack arrays a and b vertically

In [18]:
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)
c=np.concatenate([a, b], axis=0)
c

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

- Stack the arrays a and b horizontally.

In [19]:
d=np.concatenate([a, b], axis=1)
d

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?

- Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [21]:
e=np.array([1,2,3])
e=np.r_[np.repeat(e, 3), np.tile(e, 3)]
e

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. How to get the common items between two python numpy arrays?

- Get the common items between a and b

In [23]:
f = np.array([1,2,3,2,3,4,3,4,5,6])
g = np.array([7,2,10,2,7,4,9,4,9,8])
h=np.intersect1d(f,g)
h

array([2, 4])

12. How to remove from one array those items that exist in another?

- From array a remove all items present in array b

In [24]:
i = np.array([1,2,3,4,5])
j = np.array([5,6,7,8,9])
np.setdiff1d(i,j)


array([1, 2, 3, 4])