In [3]:
import numpy as np

1- Crear una matriz de 5x5 con valores en las filas de 0 a 4


In [4]:
matriz=np.zeros(25) # Creacion de la matriz en ceros
matriz

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
matriz=matriz.reshape(5,5) # definir filas y columnas
matriz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
arreglo=np.arange(5) #crear un arreglo del 0 al 4
arreglo

array([0, 1, 2, 3, 4])

In [7]:
matriz=matriz+arreglo # sumar la matriz y el arreglo
matriz

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

2- Crear un vector de tamano 30 y encontar su promedio

In [8]:
vector=np.random.randint(1,101, size=30) # se crea un arreglo de 30 items aleatorios entre 1 y 100.
vector

array([20, 71, 55, 11,  8, 37, 69, 88, 23, 48, 43, 41, 72, 44, 15, 88, 93,
       89, 96, 63,  2, 88, 71, 66, 77, 45, 99, 20, 11, 53])

In [9]:
vector.mean() #se calcula el promedio

53.53333333333333

3- Normalizar una matrz 5x5

In [10]:
matriz2=np.random.randint(1,101, size=25) #creacion de matriz con 25 items
matriz2



array([ 80,  69,  28,  32,   7,  41,  37,  43,   2,   1,   7,  49,  86,
         6,  76,  32,  89,  67, 100,   7,  71,  64,  30,  91,  95])

In [11]:
matriz2=matriz2.reshape(5,5) # se da forma de matriz
matriz2

array([[ 80,  69,  28,  32,   7],
       [ 41,  37,  43,   2,   1],
       [  7,  49,  86,   6,  76],
       [ 32,  89,  67, 100,   7],
       [ 71,  64,  30,  91,  95]])

In [12]:
media=np.mean(matriz2) # Se calcula la media
media

48.4

In [13]:
desvio=np.std(matriz2)
desvio

32.15089423328689

In [14]:
(matriz2[0,0]-media)/desvio  #Desvio para un unico item

0.9828653526931599

In [15]:
(matriz2-media)/desvio #Desvio para toda la matriz

array([[ 0.98286535,  0.64072868, -0.63450801, -0.51009468, -1.28767803],
       [-0.23016467, -0.35457801, -0.167958  , -1.4431947 , -1.47429803],
       [-1.28767803,  0.018662  ,  1.16948536, -1.31878136,  0.85845202],
       [-0.51009468,  1.26279536,  0.57852201,  1.60493203, -1.28767803],
       [ 0.70293535,  0.48521201, -0.57230134,  1.32500203,  1.44941536]])

In [16]:
for i in range(5):
  for j in range(5):
    print(matriz[i,j])

0.0
1.0
2.0
3.0
4.0
0.0
1.0
2.0
3.0
4.0
0.0
1.0
2.0
3.0
4.0
0.0
1.0
2.0
3.0
4.0
0.0
1.0
2.0
3.0
4.0
