<a href="https://colab.research.google.com/github/chmedinap/PracticasNumpy/blob/master/PracticaNumpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1- Crear una matriz de 5x5 con valores en las filas de 0 a 4

In [9]:
matriz=np.zeros(25) # Creacion de la matriz en ceros
matriz


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
matriz=matriz.reshape(5,5) # definir filas y columnas
matriz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
arreglo=np.arange(5) #crear un arreglo del 0 al 4
arreglo

array([0, 1, 2, 3, 4])

In [12]:
matriz=matriz+arreglo # sumar la matriz y el arreglo
matriz

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

2- Crear un vector de tamano 30 y encontar su promedio

In [15]:
vector=np.random.randint(1,101, size=30) # se crea un arreglo de 30 items aleatorios entre 1 y 100.
vector

array([93, 31, 29, 89, 98, 54, 29, 97, 22, 44, 23, 38, 27,  3,  5, 56, 89,
       85, 89, 28, 52, 35, 10, 30,  8, 58, 93, 90, 77, 93])

In [16]:
vector.mean() #se calcula el promedio


52.5

3- Normalizar una matrz 5x5

In [18]:
matriz2=np.random.randint(1,101, size=25) creacion de matriz con 25 items
matriz2

array([ 47,  73,  60,  30,  53,  28,  34,  33,  54,  65,   8,  60,  97,
         2,  64,  30,  29,  88,   8,  11, 100,  12,   3,  26,  93])

In [19]:
matriz2=matriz2.reshape(5,5) # se da forma de matriz
matriz2

array([[ 47,  73,  60,  30,  53],
       [ 28,  34,  33,  54,  65],
       [  8,  60,  97,   2,  64],
       [ 30,  29,  88,   8,  11],
       [100,  12,   3,  26,  93]])

In [20]:
media=np.mean(matriz2) # Se calcula la media
media

44.32

In [21]:
desvio=np.std(matriz2)
desvio

29.820422532217748

In [22]:
(matriz2[0,0]-media)/desvio  #Desvio para un unico item

0.08987129532133721

In [23]:
(matriz2-media)/desvio #Desvio para toda la matriz

array([[ 0.0898713 ,  0.961757  ,  0.52581415, -0.48020782,  0.29107569],
       [-0.54727595, -0.34607156, -0.37960562,  0.32460975,  0.69348447],
       [-1.21795726,  0.52581415,  1.76657457, -1.41916165,  0.65995041],
       [-0.48020782, -0.51374188,  1.46476798, -1.21795726, -1.11735506],
       [ 1.86717676, -1.08382099, -1.38562758, -0.61434408,  1.6324383 ]])

Imprimir cada item de las dos matrices creadas

In [25]:
for i in range(5):
  for j in range(5):
    print(matriz[i,j])

0.0
1.0
2.0
3.0
4.0
0.0
1.0
2.0
3.0
4.0
0.0
1.0
2.0
3.0
4.0
0.0
1.0
2.0
3.0
4.0
0.0
1.0
2.0
3.0
4.0


In [26]:
for i in range(5):
  for j in range(5):
    print(matriz2[i,j])

47
73
60
30
53
28
34
33
54
65
8
60
97
2
64
30
29
88
8
11
100
12
3
26
93
